### ISSUE TITLE
Request for Python Files from Your Informative Video

### ISSUE THREAD

**Issue by sallyoneee** [Brendan-Kirtlan/Minecraft-file-encoder#1]
Hey, I really enjoyed your video. You explained everything so clearly and made it look easy. I was wondering if you could share the Python files you used in the video with us? I would love to try them out myself and learn from your code. Thanks a lot for your awesome work!

**Comment by Brendan-Kirtlan** [comment]
Sure! I forgot to upload the Python files but I’ll definitely do that when
I get home. I’m out town at the moment but I’ll be back soon. Check back
later in the week and they’ll be there.

**Comment by Brendan-Kirtlan** [comment]
The files for the frequency and the decrypting have been uploaded.
