### ISSUE TITLE
Questions for .jar

### ISSUE THREAD

**Issue by ArloRuzt** [Brendan-Kirtlan/Minecraft-file-encoder#2]
What libraries and engines do we need to properly compile this Java program into a .jar, and where do we put it after compiling? 

How do we run it?

Will there be an in-depth tutorial on how to fully compress and uncompress an mp4 file, etc?

These are all the questions that I could think of.

**Comment by Brendan-Kirtlan** [comment]
https://www.youtube.com/watch?v=dem7dujCDvg
This was the video I used to see how to set everything up. I did it in Intellij Idea which makes it 100x easier than a more basic IDE like Eclipse but it is a paid IDE (or free for students).
For the encoding, if you look at the source code I just defined a file path which you can replace for whatever file you want to encode, then just compile the plugin. The decoding just puts the plugin into the server folder. 
With bukkit servers, there's a folder in your server folder where you place your plugins. All you do is drag the compiled jar file into the plugin folder then start the server. If you have any other questions, please let me know and I'll be happy to help.

**Comment by DubiousDodo** [comment]
Is there a location where the decoded file is put into?
